# -*- coding: utf-8 -*-
"""rstar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnC0lM6InsJl-7O8zsXMlmQYu5THYGot
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/rStar

!git clone https://github.com/microsoft/rStar
!pip install -r rStar/requirements.txt

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/MARIO-Math-Reasoning/MARIO_EVAL.git
# %cd MARIO_EVAL
# %cd latex2sympy
# %pip install .
# %cd ..
# %pip install -e .
# %cd ..

!git clone https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/rStar/rStar

!export CUDA_VISIBLE_DEVICES="0"

!python main.py --qaf /content/drive/MyDrive/rStar/output.json --custom_cfg /content/drive/MyDrive/rStar/rStar/config/sample_mcts.yaml --model_dir /content/drive/MyDrive/rStar/DeepSeek-R1-Distill-Qwen-1.5B

!export CUDA_VISIBLE_DEVICES="0"

!python rStar/main.py --qaf output.json --custom_cfg rStar/config/sft_sample_mcts.yaml --model_dir DeepSeek-R1-Distill-Qwen-1.5B --reward_model_dir rm